[theme]
base = "light"
primaryColor = "#008C95"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#10233F"
font = "sans serif"

[server]
headless = false

[browser]
gatherUsageStats = false
